project:
  type: website
  output-dir: docs
website:
  title: "GAMLSS talk 2025"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - talk_2.qmd

      
sidebar:
  contents: auto
      
format:
  html:
    theme: sky
    css: styles.css
    toc: true

editor: visual

